version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
      AIRFLOW__WEBSERVER__SECRET_KEY: "lIWYKyUjKAX6zUKvUZJPIxjZtvYjvR9RX92VkNytDd3eVPtH-C8A1CgldBVaTeL0u2HiXHjkmSA"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl_project:/opt/airflow/etl
    command: >
      bash -c "
        airflow db init &&
        airflow users create \
          --username admin \
          --password admin \
          --role Admin \
          --email imranndubai@icloud.com
      "

  airflow-webserver:
    image: apache/airflow:2.9.2
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
      AIRFLOW__WEBSERVER__SECRET_KEY: "lIWYKyUjKAX6zUKvUZJPIxjZtvYjvR9RX92VkNytDd3eVPtH-C8A1CgldBVaTeL0u2HiXHjkmSA"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
      - ./etl_project:/opt/airflow/etl
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.9.2
    depends_on:
      - postgres
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres/airflow"
      AIRFLOW__WEBSERVER__SECRET_KEY: "lIWYKyUjKAX6zUKvUZJPIxjZtvYjvR9RX92VkNytDd3eVPtH-C8A1CgldBVaTeL0u2HiXHjkmSA"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
      - ./etl_project:/opt/airflow/etl
    command: airflow scheduler

volumes:
  postgres_data: